"""
ledger/regulatory/package.py — Regulatory Examination Package Generator (Phase 6 Bonus)

Generates a self-contained, cryptographically verifiable examination package for regulators
and risk audit teams examining an AI-driven commercial loan decision.

Contents:
1. Complete, ordered event stream with full payloads and metadata.
2. Exact state of every projection as it existed at examination_date (temporal time-travel).
3. Cryptographic audit chain verification and tamper detection results.
4. Human-readable narrative generated by replaying events into plain English.
5. AI Agent governance metadata: model versions, confidence scores, and input data hashes.
6. Package-level SHA-256 integrity signature for independent verification.
"""
from __future__ import annotations
import hashlib
import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from ledger.integrity.audit_chain import run_integrity_check
from ledger.projections.application_summary import ApplicationSummaryProjection
from ledger.projections.compliance_audit import ComplianceAuditProjection
from ledger.event_store import InMemoryEventStore


@dataclass
class RegulatoryPackage:
    """Self-contained regulatory audit package."""
    application_id: str
    examination_date: str | None
    generated_at: str
    total_events: int
    event_stream: list[dict[str, Any]]
    projection_states_at_examination_date: dict[str, Any]
    integrity_verification: dict[str, Any]
    narrative_lifecycle: list[str]
    agent_governance_metadata: list[dict[str, Any]]
    package_signature_sha256: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "application_id": self.application_id,
            "examination_date": self.examination_date,
            "generated_at": self.generated_at,
            "total_events": self.total_events,
            "event_stream": self.event_stream,
            "projection_states_at_examination_date": self.projection_states_at_examination_date,
            "integrity_verification": self.integrity_verification,
            "narrative_lifecycle": self.narrative_lifecycle,
            "agent_governance_metadata": self.agent_governance_metadata,
            "package_signature_sha256": self.package_signature_sha256,
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent, default=str)


def _generate_event_narrative(event: dict) -> str:
    """Converts a domain event into a clear, plain-English regulatory summary sentence."""
    etype = event.get("event_type", "Unknown")
    payload = event.get("payload", {}) or {}
    ts = event.get("recorded_at") or event.get("metadata", {}).get("recorded_at") or "unknown time"

    if etype == "ApplicationSubmitted":
        amt = payload.get("requested_amount_usd", "N/A")
        applicant = payload.get("applicant_id", "Unknown")
        purpose = payload.get("loan_purpose", "commercial loan")
        return f"Applicant '{applicant}' submitted application for ${amt:,.2f} ({purpose}) at {ts}."

    elif etype == "DocumentUploadRequested":
        docs = payload.get("required_document_types", [])
        return f"System requested mandatory documentation: {', '.join(docs)}."

    elif etype == "DocumentUploaded":
        doc_id = payload.get("document_id", "document")
        return f"Document '{doc_id}' was uploaded and staged for financial ingestion."

    elif etype == "DocumentsProcessed":
        return f"Automated document processing extracted GAAP financial statements and verified data consistency."

    elif etype == "CreditAnalysisRequested":
        return f"Credit analysis was queued and assigned to CreditAnalysisAgent."

    elif etype == "AgentSessionStarted":
        agent_type = payload.get("agent_type", payload.get("agent_id", "Agent"))
        mv = payload.get("model_version", "v1")
        ctx = payload.get("context_source", "fresh")
        return f"AI Agent '{agent_type}' initialized session under model version '{mv}' (context: {ctx})."

    elif etype == "CreditAnalysisCompleted":
        decision = payload.get("decision", {}) if isinstance(payload.get("decision"), dict) else payload
        risk = decision.get("risk_tier", payload.get("risk_tier", "MEDIUM"))
        rec_limit = decision.get("recommended_limit_usd", payload.get("recommended_limit_usd", 0))
        conf = decision.get("confidence", payload.get("confidence_score", 0.0))
        mv = payload.get("model_version", "unknown")
        return f"Credit analysis completed by model {mv}: evaluated risk as '{risk}' with confidence {conf:.2f}, recommending limit ${rec_limit:,.2f}."

    elif etype == "FraudScreeningRequested":
        return f"Fraud screening was triggered and assigned to FraudDetectionAgent."

    elif etype == "FraudScreeningCompleted":
        score = payload.get("fraud_score", 0.0)
        risk = payload.get("risk_level", "LOW")
        rec = payload.get("recommendation", "PASS")
        return f"Fraud screening completed: fraud score {score:.2f} (risk tier: {risk}), resulting in recommendation '{rec}'."

    elif etype == "ComplianceCheckRequested" or etype == "ComplianceCheckInitiated":
        reg_ver = payload.get("regulation_set_version", "2026-Q1")
        rules = payload.get("rules_to_evaluate", payload.get("checks_required", []))
        return f"Compliance check initiated against regulatory framework '{reg_ver}' for rules: {rules}."

    elif etype == "ComplianceRulePassed":
        rule = payload.get("rule_id", "rule")
        return f"Compliance rule '{rule}' PASSED regulatory verification."

    elif etype == "ComplianceRuleFailed":
        rule = payload.get("rule_id", "rule")
        reason = payload.get("failure_reason", "rule criteria not satisfied")
        hard = " (HARD BLOCK)" if payload.get("is_hard_block") else ""
        return f"Compliance rule '{rule}' FAILED: {reason}{hard}."

    elif etype == "DecisionRequested":
        return f"Decision synthesis queued for DecisionOrchestratorAgent."

    elif etype == "DecisionGenerated":
        rec = payload.get("recommendation", "UNKNOWN")
        conf = payload.get("confidence", 0.0)
        orch = payload.get("orchestrator_agent_id", payload.get("orchestrator_session_id", "DecisionOrchestrator"))
        return f"DecisionOrchestrator '{orch}' synthesized multi-agent analyses and generated recommendation '{rec}' (confidence: {conf:.2f})."

    elif etype == "HumanReviewRequested":
        reason = payload.get("reason", "manual review required")
        return f"Application routed to human loan officer review queue (reason: {reason})."

    elif etype == "HumanReviewCompleted":
        rev = payload.get("reviewer_id", "Officer")
        dec = payload.get("final_decision", "DECISION")
        override = payload.get("override", False)
        override_txt = f" with override: {payload.get('override_reason', '')}" if override else ""
        return f"Human loan officer '{rev}' completed review with final decision '{dec}'{override_txt}."

    elif etype == "ApplicationApproved":
        amt = payload.get("approved_amount_usd", 0)
        by = payload.get("approved_by", "system")
        return f"Application APPROVED for ${amt:,.2f} by '{by}'."

    elif etype == "ApplicationDeclined":
        reasons = payload.get("decline_reasons", [])
        return f"Application DECLINED. Adverse action reasons: {reasons}."

    elif etype == "AuditIntegrityCheckRun":
        valid = payload.get("chain_valid", True)
        count = payload.get("events_verified_count", 0)
        return f"Cryptographic audit integrity verification executed: {count} events verified (chain valid: {valid})."

    return f"Event '{etype}' recorded with payload attributes: {list(payload.keys())}."


async def generate_regulatory_package(
    store,
    application_id: str,
    examination_date: str | datetime | None = None,
) -> RegulatoryPackage:
    """
    Generates a complete, self-contained regulatory audit package.
    """
    exam_dt_str = None
    exam_cutoff = None
    if examination_date:
        if isinstance(examination_date, datetime):
            exam_cutoff = examination_date
            exam_dt_str = examination_date.isoformat()
        else:
            exam_dt_str = str(examination_date)
            try:
                exam_cutoff = datetime.fromisoformat(exam_dt_str.replace("Z", "+00:00"))
            except Exception:
                exam_cutoff = None

    # 1. Load all streams for application
    loan_stream_id = f"loan-{application_id}"
    credit_stream_id = f"credit-{application_id}"
    fraud_stream_id = f"fraud-{application_id}"
    compliance_stream_id = f"compliance-{application_id}"
    audit_stream_id = f"audit-loan-{application_id}"

    all_raw: list[dict] = []
    for sid in [loan_stream_id, credit_stream_id, fraud_stream_id, compliance_stream_id, audit_stream_id]:
        stream_events = await store.load_stream(sid)
        all_raw.extend(stream_events)

    # Sort globally by recorded_at / position
    def _sort_key(ev: dict):
        rec = ev.get("recorded_at") or ""
        gpos = ev.get("global_position", 0)
        spos = ev.get("stream_position", 0)
        return (str(rec), gpos, spos)

    all_events = sorted(all_raw, key=_sort_key)

    # Filter events up to examination_date if provided
    examined_events: list[dict] = []
    for ev in all_events:
        if exam_cutoff:
            rec_str = ev.get("recorded_at")
            if rec_str:
                try:
                    dt = datetime.fromisoformat(str(rec_str).replace("Z", "+00:00"))
                    if dt > exam_cutoff:
                        continue
                except Exception:
                    pass
        examined_events.append(ev)

    # 2. Replay projection states as of examination_date
    app_proj = ApplicationSummaryProjection()
    comp_proj = ComplianceAuditProjection()
    isolated_store = InMemoryEventStore()

    for ev in examined_events:
        await app_proj.handle(isolated_store, ev)
        await comp_proj.handle(isolated_store, ev)

    app_summary_state = app_proj.get_application(application_id) or {}
    compliance_state = comp_proj.get_compliance(application_id, as_of=exam_dt_str) or {}

    projection_states = {
        "as_of_timestamp": exam_dt_str or datetime.now(timezone.utc).isoformat(),
        "application_summary": app_summary_state,
        "compliance_audit_view": compliance_state,
    }

    # 3. Cryptographic integrity check
    integrity_res = await run_integrity_check(store, "loan", application_id)
    integrity_data = {
        "chain_valid": integrity_res.chain_valid,
        "tamper_detected": integrity_res.tamper_detected,
        "events_verified": integrity_res.events_verified,
        "integrity_hash": integrity_res.integrity_hash,
        "previous_hash": integrity_res.previous_hash,
        "full_replay_integrity_hash": integrity_res.full_replay_integrity_hash,
    }

    # 4. Generate plain-English narrative lifecycle
    narrative: list[str] = []
    for ev in examined_events:
        narrative.append(_generate_event_narrative(ev))

    # 5. Extract AI agent governance metadata
    agent_metadata: list[dict[str, Any]] = []
    seen_sessions = set()
    for ev in examined_events:
        etype = ev.get("event_type")
        payload = ev.get("payload", {}) or {}

        if etype in ("CreditAnalysisCompleted", "FraudScreeningCompleted", "DecisionGenerated", "AgentSessionStarted"):
            sess = payload.get("session_id") or payload.get("orchestrator_session_id")
            if sess and sess not in seen_sessions:
                seen_sessions.add(sess)
                decision = payload.get("decision", {}) if isinstance(payload.get("decision"), dict) else payload
                agent_metadata.append({
                    "event_type": etype,
                    "session_id": sess,
                    "agent_type": payload.get("agent_type", payload.get("agent_id", etype)),
                    "model_version": payload.get("model_version", payload.get("screening_model_version", payload.get("model_versions"))),
                    "confidence_score": decision.get("confidence", payload.get("confidence", payload.get("confidence_score"))),
                    "input_data_hash": payload.get("input_data_hash", "N/A"),
                    "recorded_at": ev.get("recorded_at"),
                })

    # 6. Package signature (SHA-256 over canonical package payload)
    now_iso = datetime.now(timezone.utc).isoformat()
    canonical_body = {
        "application_id": application_id,
        "examination_date": exam_dt_str,
        "total_events": len(examined_events),
        "events_hash": hashlib.sha256(json.dumps(examined_events, sort_keys=True, default=str).encode("utf-8")).hexdigest(),
        "integrity_hash": integrity_data["integrity_hash"],
    }
    pkg_signature = hashlib.sha256(json.dumps(canonical_body, sort_keys=True, default=str).encode("utf-8")).hexdigest()

    return RegulatoryPackage(
        application_id=application_id,
        examination_date=exam_dt_str,
        generated_at=now_iso,
        total_events=len(examined_events),
        event_stream=examined_events,
        projection_states_at_examination_date=projection_states,
        integrity_verification=integrity_data,
        narrative_lifecycle=narrative,
        agent_governance_metadata=agent_metadata,
        package_signature_sha256=pkg_signature,
    )
